ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

######### Customize Container Here ###########
### Envrionment config
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/ubuntu/install/chrome/install_chrome.sh \
                  /ubuntu/install/vs_code/install_vs_code.sh \
                  /ubuntu/install/dbeaver/install_dbeaver.sh \
                  /ubuntu/install/eclipse/install_eclipse.sh"
### Envrionment config

RUN apt update
RUN yes | apt-get install gdebi

### Node Ini
RUN apt-get update && apt-get install -y \
  ca-certificates \
  curl
ARG NODE_VERSION=14.21.3
ARG NODE_PACKAGE=node-v$NODE_VERSION-linux-x64
ARG NODE_HOME=/opt/$NODE_PACKAGE
ENV NODE_PATH $NODE_HOME/lib/node_modules
ENV PATH $NODE_HOME/bin:$PATH
RUN curl https://nodejs.org/dist/v$NODE_VERSION/$NODE_PACKAGE.tar.gz | tar -xzC /opt/
# comes with npm
RUN npm install -g typescript
### Node End

RUN apt-get update && apt-get install --no-install-recommends --yes openssl
RUN apt-get install -y libaio1
RUN apt install unzip

RUN apt-get install git

# Descarga ficheros Opcion 1
#RUN curl -L https://github.com/flopez9t-systems/workspaces-images/archive/workspaces-images-main.zip --output /tmp/workspaces-images-main.zip
#RUN unzip ./workspaces-images-main.zip -d /tmp
#RUN rm /tmp/workspaces-images-main.zip
# Descarga ficheros Opcion 1

# Descarga ficheros Opcion 2
RUN git clone https://github.com/flopez9t-systems/workspaces-images.git /tmp/workspaces-images-main
# Descarga ficheros Opcion 2

RUN mkdir -p /dockerstartup/install/ubuntu
# Copy install scripts
RUN cp -r /tmp/workspaces-images-main/src/ubuntu $INST_DIR

# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done && \
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}
# Run installations

RUN rm -R  /tmp/workspaces-images-main

# Install sublime
RUN  wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add - \
    && apt-get update \
    && apt-get install -y apt-transport-https \
    && echo "deb https://download.sublimetext.com/ apt/stable/" |  tee /etc/apt/sources.list.d/sublime-text.list \
    && apt-get update \
    && apt-get install sublime-text \
    && cp /usr/share/applications/sublime_text.desktop $HOME/Desktop/ \
    && chmod +x $HOME/Desktop/sublime_text.desktop \
    && chown 1000:1000 $HOME/Desktop/sublime_text.desktop
# Install sublime

USER kasm-user
# install VS Code extensions
# RUN chmod 777 -R $HOME/.vscode/extensions/
RUN code --force --install-extension Gruntfuggly.activitusbar \
                 --force --install-extension usernamehw.errorlens \
                 --force --install-extension eamodio.gitlens \
                 --force --install-extension mhutchie.git-graph \
                 --force --install-extension donjayamanne.githistory \
                 --force --install-extension aaron-bond.better-comments \
                 --force --install-extension SimonSiefke.prettier-vscode \
                 --force --install-extension usernamehw.remove-empty-lines \
                 --force --install-extension spywhere.guides \
                 --force --install-extension oderwat.indent-rainbow \
                 --force --install-extension yzhang.markdown-all-in-one \
                 --force --install-extension dbaeumer.vscode-eslint \
                 --force --install-extension RapidAPI.vscode-rapidapi-client \
                 --force --install-extension RapidAPI.vscode-services \
                 --force --install-extension MS-CEINTL.vscode-language-pack-es \
                 --force --install-extension vscode-icons-team.vscode-icons \
                 --force --install-extension ms-vscode-remote.remote-containers \
                 --force --install-extension ms-azuretools.vscode-docker \
                 --force --install-extension ms-vscode-remote.remote-wsl \
                 --force --install-extension igni24.autobarrelmanager \
                 --force --install-extension formulahendry.auto-rename-tag \
                 --force --install-extension SimonSiefke.svg-preview \
                 --force --install-extension ms-vscode.js-debug-nightly \
                 --force --install-extension mgmcdermott.vscode-language-babel \
                 --force --install-extension xabikos.JavaScriptSnippets \
                 --force --install-extension p42ai.refactor \
                 --force --install-extension woodreamz.es7-react-js-snippets \
                 --force --install-extension planbcoding.vscode-react-refactor \
                 --force --install-extension msjsdiag.vscode-react-native
# install VS Code extensions

# install OpenJdk 8u372-b07
# https://devopspilot.com/content/docker/tutorials/Dockerfile/02-create-a-dokerfile-for-installing-openjdk15.html
# https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html
# https://www.openlogic.com/openjdk-downloads?field_java_parent_version_target_id=416&field_operating_system_target_id=426&field_architecture_target_id=391&field_java_package_target_id=396
RUN curl https://builds.openlogic.com/downloadJDK/openlogic-openjdk/8u372-b07/openlogic-openjdk-8u372-b07-linux-x64.tar.gz | tar -xzC /tmp
ENV JAVA_HOME '/tmp/openlogic-openjdk-8u372-b07-linux-x64'
ENV PATH="$JAVA_HOME/bin:$PATH"
# install OpenJdk 8u372-b07

# install Apache maven
# https://maven.apache.org/install.html
# https://phoenixnap.com/kb/install-maven-on-ubuntu
# https://www.digitalocean.com/community/tutorials/install-maven-linux-ubuntu
RUN curl https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz | tar -xzC /tmp
# install Apache maven

# Eclipse cambiar perfil por defecto
# ~/.eclipse/org.eclipse.platform_4.3.0_1473617060_linux_gtk_x86_64/configuration/config.ini 
# osgi.instance.area.default=@user.home/workspace
# Eclipse cambiar perfil por defecto

######### End Customizations ###########

# Userspace Runtime
ENV HOME /home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]
